# Generated by Django 3.2.9 on 2021-12-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detalle',
            field=models.TextField(max_length=1000),
        ),
    ]
