# Generated by Django 3.2.9 on 2021-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0004_alter_comentario_posteo'),
        ('post', '0004_auto_20211214_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(to='comentario.Comentario'),
        ),
    ]
