# Generated by Django 4.0 on 2021-12-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0005_remove_comentario_posteo'),
        ('post', '0006_alter_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(null=True, to='comentario.Comentario'),
        ),
    ]
