# Generated by Django 4.0 on 2021-12-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_remove_categoria_autor'),
        ('post', '0007_alter_post_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(null=True, to='categoria.Categoria'),
        ),
    ]
