# Generated by Django 3.2.9 on 2021-12-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20211221_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
