# Generated by Django 3.2.9 on 2021-12-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=255)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comentario.comentario')),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
    ]
