# Generated by Django 3.2.9 on 2021-12-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_rename_comentario_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='autor',
        ),
    ]
