# Generated by Django 3.2.9 on 2021-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0003_alter_comentario_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='posteo',
            field=models.TextField(null=True),
        ),
    ]
