# Generated by Django 3.2.9 on 2021-12-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0004_alter_comentario_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='posteo',
        ),
    ]
