# Generated by Django 4.0 on 2021-12-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_comentarios'),
        ('comentario', '0005_remove_comentario_posteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='posteo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
