# Generated by Django 3.2.9 on 2021-12-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0006_auto_20211221_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='estado',
        ),
    ]
